# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_password1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#Index(3)

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from datetime import datetime
import time

class Ui_screen_password(object):
    def setupUi(self, screen_password, iot_handler):
        if self.iot_handler:
            self.cursor = self.iot_handler.cursor
        screen_password.setObjectName("screen_password")
        screen_password.resize(720, 1280)
        screen_password.setWindowFlags(QtCore.Qt.FramelessWindowHint)  # Remove title bar
        screen_password.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.centralwidget = QtWidgets.QWidget(screen_password)
        self.centralwidget.setObjectName("centralwidget")
        self.lblhotel = QtWidgets.QLabel(self.centralwidget)
        self.lblhotel.setGeometry(QtCore.QRect(210, 40, 300, 115))
        self.lblhotel.setObjectName("lblhotel")
        self.lblskc = QtWidgets.QLabel(self.centralwidget)
        self.lblskc.setGeometry(QtCore.QRect(240, 1040, 240, 114))
        self.lblskc.setObjectName("lblskc")
        self.btn_goback = QtWidgets.QPushButton(self.centralwidget)
        self.btn_goback.setGeometry(QtCore.QRect(290, 1165, 140, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_goback.setFont(font)
        self.btn_goback.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_goback.setStyleSheet("background-color: #f24962; border-radius: 15px;")
        self.btn_goback.setObjectName("btn_goback")
        self.lblenter = QtWidgets.QLabel(self.centralwidget)
        self.lblenter.setGeometry(QtCore.QRect(85, 210, 561, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(32)
        self.lblenter.setFont(font)
        self.lblenter.setObjectName("lblenter")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(260, 500, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("border-radius: 20px;")
        self.btn_2.setObjectName("btn_2")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(260, 630, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("border-radius: 20px;")
        self.btn_5.setObjectName("btn_5")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(260, 760, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("border-radius: 20px;")
        self.btn_8.setObjectName("btn_8")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(30, 890, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(27)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("border-radius: 20px;")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(30, 500, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("border-radius: 20px;")
        self.btn_1.setObjectName("btn_1")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(30, 630, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("border-radius: 20px;")
        self.btn_4.setObjectName("btn_4")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(30, 760, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("border-radius: 20px;")
        self.btn_7.setObjectName("btn_7")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(490, 630, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("border-radius: 20px;")
        self.btn_6.setObjectName("btn_6")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(490, 760, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("border-radius: 20px;")
        self.btn_9.setObjectName("btn_9")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(490, 890, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(27)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("border-radius: 20px;")
        self.btn_back.setObjectName("btn_back")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(490, 500, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("border-radius: 20px;")
        self.btn_3.setObjectName("btn_3")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(260, 890, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(46)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("border-radius: 20px;")
        self.btn_0.setObjectName("btn_0")
        self.lbl6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl6.setGeometry(QtCore.QRect(90, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl6.setFont(font)
        self.lbl6.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl6.setText("")
        self.lbl6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl6.setObjectName("lbl6")
        self.lbl5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl5.setGeometry(QtCore.QRect(182, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl5.setFont(font)
        self.lbl5.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl5.setText("")
        self.lbl5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5.setObjectName("lbl5")
        self.lbl4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl4.setGeometry(QtCore.QRect(274, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl4.setFont(font)
        self.lbl4.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl4.setText("")
        self.lbl4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl4.setObjectName("lbl4")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setGeometry(QtCore.QRect(458, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl2.setFont(font)
        self.lbl2.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl2.setText("")
        self.lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl3.setGeometry(QtCore.QRect(366, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl3.setFont(font)
        self.lbl3.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl3.setText("")
        self.lbl3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl3.setObjectName("lbl3")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(550, 320, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(42)
        self.lbl1.setFont(font)
        self.lbl1.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.lbl1.setText("")
        self.lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1.setObjectName("lbl1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 740, 1300))
        self.frame.setStyleSheet("border: 15px solid black; border-radius: 35px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.lblskc.raise_()
        self.btn_goback.raise_()
        self.lblhotel.raise_()
        self.lblenter.raise_()
        self.btn_2.raise_()
        self.btn_5.raise_()
        self.btn_8.raise_()
        self.btn_clear.raise_()
        self.btn_1.raise_()
        self.btn_4.raise_()
        self.btn_7.raise_()
        self.btn_6.raise_()
        self.btn_9.raise_()
        self.btn_back.raise_()
        self.btn_3.raise_()
        self.btn_0.raise_()
        self.lbl6.raise_()
        self.lbl5.raise_()
        self.lbl4.raise_()
        self.lbl2.raise_()
        self.lbl3.raise_()
        self.lbl1.raise_()

        screen_password.setCentralWidget(self.centralwidget)
        self.retranslateUi(screen_password)
        QtCore.QMetaObject.connectSlotsByName(screen_password)

        self.password = ''
        self.display = [self.lbl1,self.lbl2,self.lbl3,self.lbl4,self.lbl5,self.lbl6]
        self.btn = [self.btn_0,self.btn_1,self.btn_2,self.btn_3,self.btn_4,self.btn_5,self.btn_6,self.btn_7,self.btn_8,self.btn_9]

        # Connect button signals to methods
        self.btn_0.clicked.connect(lambda: self.add_digit("0"))
        self.btn_1.clicked.connect(lambda: self.add_digit("1"))
        self.btn_2.clicked.connect(lambda: self.add_digit("2"))
        self.btn_3.clicked.connect(lambda: self.add_digit("3"))
        self.btn_4.clicked.connect(lambda: self.add_digit("4"))
        self.btn_5.clicked.connect(lambda: self.add_digit("5"))
        self.btn_6.clicked.connect(lambda: self.add_digit("6"))
        self.btn_7.clicked.connect(lambda: self.add_digit("7"))
        self.btn_8.clicked.connect(lambda: self.add_digit("8"))
        self.btn_9.clicked.connect(lambda: self.add_digit("9"))
        self.btn_clear.clicked.connect(lambda: self.add_digit("clear"))
        self.btn_back.clicked.connect(lambda: self.add_digit("back"))
        self.btn_goback.clicked.connect(self.go_back_clicked)

    def retranslateUi(self, screen_password):
        _translate = QtCore.QCoreApplication.translate
        screen_password.setWindowTitle(_translate("screen_password", "screen_password"))
        self.lblhotel.setText(_translate("screen_password", "<html><head/><body><p><img src=\":/Cllix logo/cllix-logo_300-115.png\"/></p></body></html>"))
        self.lblskc.setText(_translate("screen_password", "<html><head/><body><p><img src=\":/SKCLogo/SKC_240-114.jpg\"/></p></body></html>"))
        self.btn_goback.setText(_translate("screen_password", "Home"))
        self.lblenter.setText(_translate("screen_password", "Please enter admin password"))
        self.btn_0.setText(_translate("screen_password", "0"))
        self.btn_1.setText(_translate("screen_password", "1"))
        self.btn_2.setText(_translate("screen_password", "2"))
        self.btn_3.setText(_translate("screen_password", "3"))
        self.btn_4.setText(_translate("screen_password", "4"))
        self.btn_5.setText(_translate("screen_password", "5"))
        self.btn_6.setText(_translate("screen_password", "6"))
        self.btn_7.setText(_translate("screen_password", "7"))
        self.btn_8.setText(_translate("screen_password", "8"))
        self.btn_9.setText(_translate("screen_password", "9"))
        self.btn_clear.setText(_translate("screen_password", "Clear all"))
        self.btn_back.setText(_translate("screen_password", "Back"))
        self.btn_0.setText(_translate("screen_password", "0"))
        self.btn_1.setText(_translate("screen_password", "1"))
        self.btn_3.setText(_translate("screen_password", "3"))
        self.btn_4.setText(_translate("screen_password", "4"))
        self.btn_6.setText(_translate("screen_password", "6"))
        self.btn_7.setText(_translate("screen_password", "7"))
        self.btn_9.setText(_translate("screen_password", "9"))

    def check_db(self,password):
        db_output= []
        try:
            select_query = """SELECT * FROM smartkeycaddyuser.adminuser WHERE "passcode" = %s;"""
            self.cursor.execute(select_query,(password,))
            db_output = self.cursor.fetchall()
            user = db_output[0][0],db_output[0][1],db_output[0][3],db_output[0][4]
        except Exception as e:
            user = "Incorect password"
            print(f"DB operation failed: {e}")
        return(user)

    def go_back_clicked(self):
        self.password = ''
        self.enable_btn()
        for label in self.display:
            label.setText(None)
        self.parent().setCurrentIndex(0)

    def add_digit(self,val):
#        print(len(self.password),self.password)
        if len(self.password)==5:
            self.disable_btn()
        if val == "back":
            self.password = self.password[:-1]
        elif val == "clear":
            self.password = ""
        else:
            self.disable_btn()
            self.password = self.password+val
        update = self.update_display(self.password)
        QApplication.processEvents()  
        if update == "reset_display":
            time.sleep(1)
            self.clear_all()
    
    def clear_all(self):
        for label in self.display:
            label.setText(None)
        self.password = ""
        self.enable_btn()

    def update_display(self,text):
        output ="more"
        for label in self.display:
            label.setText(None)
        for i in range(len(text)):
            self.display[i].setText(text[-i-1])
            QApplication.processEvents()
        if len(text) < 6:
            self.enable_btn()
        elif len(text) == 6:
            admin_details = self.check_db(text)
#            print(admin_details)
            if admin_details == "Incorect password":
                self.clear_all()
                output = "reset_display"
            else:
                self.clear_all()
                output = "reset_display"
                self.parent().setCurrentIndex(7)
        return(output)

    def disable_btn(self):
        for button in self.btn:
            button.setEnabled(False)

    def enable_btn(self):
        for button in self.btn:
            button.setEnabled(True)

import screens.SKC_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    screen_password = QtWidgets.QMainWindow()
    ui = Ui_screen_password()
    ui.setupUi(screen_password)
    screen_password.show()
    sys.exit(app.exec_())